load("@rules_python//python:defs.bzl", "py_binary")
load("@python_deps//:requirements.bzl", "requirement")


py_binary(
    name = "main",
    srcs = [
    "src/game_engine/Core.py",
    "src/game_engine/controllers/Controller.py",
    "src/game_engine/controllers/TrainAIController.py",
    "src/game_engine/controllers/__init__.py",
    "src/game_engine/entities/Car.py",
    "src/game_engine/entities/MusicPlayer.py",
    "src/game_engine/entities/ObjectFactory.py",
    "src/game_engine/entities/ParkingPlace.py",
    "src/game_engine/entities/obstacles/MovableObstacle.py",
    "src/game_engine/entities/obstacles/StaticObstacle.py",
    "src/game_engine/scenes/BuildScene.py",
    "src/game_engine/scenes/LearningScene.py",
    "src/game_engine/scenes/StartScene.py",
    "src/game_engine/scenes/__init__.py",
    "src/game_engine/scenes/fun_scenes/GameOfLifeScene.py",
    "src/game_engine/scenes/fun_scenes/PhysicScene.py",
    "src/game_engine/scenes/game_scene/CollisionHandlers.py",
    "src/game_engine/scenes/game_scene/DevScene.py",
    "src/game_engine/scenes/game_scene/GameSceneCore.py",
    "src/game_engine/scenes/game_scene/SceneSetup.py",
    "src/game_engine/scenes/game_scene/modes/A2BScene.py",
    "src/game_engine/scenes/game_scene/modes/ParkMeScene.py",
    "src/game_engine/scenes/game_scene/modes/PMSScreenScene.py",
    "src/game_engine/scenes/game_scene/modes/SurvivalScene.py",
    "src/game_engine/scenes/layouts/CreditsLayout.py",
    "src/game_engine/scenes/layouts/EscapeLayout.py",
    "src/game_engine/scenes/layouts/SettingLayout.py",
    "src/game_engine/scenes/layouts/__init__.py",
    "src/physics/models/CarPhysicsModel.py",
    "src/physics/models/MovableObstaclePhysicsModel.py",
    "src/physics/models/ParkingPlacePhysicModel.py",
    "src/physics/models/StaticObstaclePhysicsModel.py",
    "src/render/MimicTexture.py",
    "src/render/Window.py",
    "src/render/animator/BasicAnimator.py",
    "src/render/animator/FloatingAnimator.py",
    "src/render/animator/MoverAnimator.py",
    "src/render/animator/WanderAnimator.py",
    "src/render/animator/__init__.py",
    "src/render/particle/ParticleShow.py",
    "src/render/particle/__init__.py",
    "src/render/scene_elements/Camera.py",
    "src/render/scene_elements/RenderGroup.py",
    "src/render/scene_elements/__init__.py",
    "src/render/screen_elements/effect_animator/BasicEffect.py",
    "src/render/screen_elements/effect_animator/EffectAnimator.py",
    "src/render/screen_elements/effect_animator/__init__.py",
    "src/render/screen_elements/effect_animator/effects/FadeEffect.py",
    "src/render/screen_elements/effect_animator/effects/TextPrinter.py",
    "src/render/screen_elements/ui_components/__init__.py",
    "src/render/screen_elements/ui_components/ui_sprites/Indicator.py",
    "src/render/screen_elements/ui_components/ui_sprites/NavCircle.py",
    "src/render/screen_elements/ui_components/ui_sprites/ScoreDisplay.py",
    "src/render/screen_elements/ui_components/ui_widgets/UIAnimatorWidget.py",
    "src/render/screen_elements/ui_components/ui_widgets/UICheckButton.py",
    "src/render/screen_elements/ui_components/ui_widgets/UIFullScreenLayout.py",
    "src/render/screen_elements/ui_components/ui_widgets/UISlider.py",
    "src/render/screen_elements/ui_components/ui_widgets/UISuperAnchorWidget.py",
    "src/render/screen_elements/ui_components/ui_widgets/UISuperText.py",
    "src/render/screen_elements/ui_components/ui_widgets/UITexture.py",
    "src/render/sprites/BasicDrawable.py",
    "src/render/sprites/BasicRect.py",
    "src/render/sprites/BasicSprite.py",
    "src/render/sprites/__init__.py",
    "src/utils/ExtraClasses.py",
    "src/utils/Loaders.py",
    "src/utils/__init__.py",
    "models/DQNPolicy.py",
    "main.py"
    ],
    deps = [
    requirement("arcade"),
    requirement("attrs"),
    requirement("black"),
    requirement("cffi"),
    requirement("click"),
    requirement("cloudpickle"),
    requirement("colorama"),
    requirement("contourpy"),
    requirement("cycler"),
    requirement("Farama-Notifications"),
    requirement("filelock"),
    requirement("flake8"),
    requirement("fonttools"),
    requirement("fsspec"),
    requirement("gymnasium"),
    requirement("iniconfig"),
    requirement("intel-openmp"),
    requirement("Jinja2"),
    requirement("joblib"),
    requirement("kiwisolver"),
    requirement("MarkupSafe"),
    requirement("matplotlib"),
    requirement("mccabe"),
    requirement("mkl"),
    requirement("mpmath"),
    requirement("mypy-extensions"),
    requirement("neat-python"),
    requirement("networkx"),
    requirement("numpy"),
    requirement("packaging"),
    requirement("pandas"),
    requirement("pathspec"),
    requirement("Pillow"),
    requirement("platformdirs"),
    requirement("pluggy"),
    requirement("pycodestyle"),
    requirement("pycparser"),
    requirement("pyflakes"),
    requirement("pyglet"),
    requirement("pymunk"),
    requirement("pyparsing"),
    requirement("pytest"),
    requirement("python-dateutil"),
    requirement("pytiled-parser"),
    requirement("pytz"),
    requirement("scikit-learn"),
    requirement("scipy"),
    requirement("six"),
    requirement("stable_baselines3"),
    requirement("sympy"),
    requirement("tbb"),
    requirement("threadpoolctl"),
    requirement("torch"),
    requirement("typing_extensions"),
    requirement("tzdata")
    ],
)
